/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.ts';
import type { AuthControllerRegister201Response, LoginDto, RegisterDto } from '../models/index.ts';
import {
  AuthControllerRegister201ResponseFromJSON,
  AuthControllerRegister201ResponseToJSON,
  LoginDtoFromJSON,
  LoginDtoToJSON,
  RegisterDtoFromJSON,
  RegisterDtoToJSON,
} from '../models/index.ts';

export interface AuthControllerLoginRequest {
  loginDto: LoginDto;
}

export interface AuthControllerRegisterRequest {
  registerDto: RegisterDto;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Creates request options for authControllerLogin without sending the request
   */
  async authControllerLoginRequestOpts(
    requestParameters: AuthControllerLoginRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['loginDto'] == null) {
      throw new runtime.RequiredError(
        'loginDto',
        'Required parameter "loginDto" was null or undefined when calling authControllerLogin().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/auth/login`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: LoginDtoToJSON(requestParameters['loginDto']),
    };
  }

  /**
   * Login with email and password
   */
  async authControllerLoginRaw(
    requestParameters: AuthControllerLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthControllerRegister201Response>> {
    const requestOptions = await this.authControllerLoginRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthControllerRegister201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Login with email and password
   */
  async authControllerLogin(
    requestParameters: AuthControllerLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthControllerRegister201Response> {
    const response = await this.authControllerLoginRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for authControllerRegister without sending the request
   */
  async authControllerRegisterRequestOpts(
    requestParameters: AuthControllerRegisterRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['registerDto'] == null) {
      throw new runtime.RequiredError(
        'registerDto',
        'Required parameter "registerDto" was null or undefined when calling authControllerRegister().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/auth/register`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: RegisterDtoToJSON(requestParameters['registerDto']),
    };
  }

  /**
   * Register a new user
   */
  async authControllerRegisterRaw(
    requestParameters: AuthControllerRegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthControllerRegister201Response>> {
    const requestOptions = await this.authControllerRegisterRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthControllerRegister201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Register a new user
   */
  async authControllerRegister(
    requestParameters: AuthControllerRegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthControllerRegister201Response> {
    const response = await this.authControllerRegisterRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
