/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.ts';
import type { HealthControllerCheck200Response } from '../models/index.ts';
import {
  HealthControllerCheck200ResponseFromJSON,
  HealthControllerCheck200ResponseToJSON,
} from '../models/index.ts';

/**
 *
 */
export class HealthApi extends runtime.BaseAPI {
  /**
   * Creates request options for healthControllerCheck without sending the request
   */
  async healthControllerCheckRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/health`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Health check
   */
  async healthControllerCheckRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthControllerCheck200Response>> {
    const requestOptions = await this.healthControllerCheckRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HealthControllerCheck200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Health check
   */
  async healthControllerCheck(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthControllerCheck200Response> {
    const response = await this.healthControllerCheckRaw(initOverrides);
    return await response.value();
  }
}
