/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.ts';
import type {
  CreateTaskListDto,
  TaskListsControllerCreate201Response,
  TaskListsControllerFindAll200Response,
  UpdateTaskListDto,
  UpdateTaskListOrderDto,
} from '../models/index.ts';
import {
  CreateTaskListDtoFromJSON,
  CreateTaskListDtoToJSON,
  TaskListsControllerCreate201ResponseFromJSON,
  TaskListsControllerCreate201ResponseToJSON,
  TaskListsControllerFindAll200ResponseFromJSON,
  TaskListsControllerFindAll200ResponseToJSON,
  UpdateTaskListDtoFromJSON,
  UpdateTaskListDtoToJSON,
  UpdateTaskListOrderDtoFromJSON,
  UpdateTaskListOrderDtoToJSON,
} from '../models/index.ts';

export interface TaskListsControllerCreateRequest {
  createTaskListDto: CreateTaskListDto;
}

export interface TaskListsControllerDeleteRequest {
  id: string;
}

export interface TaskListsControllerUpdateRequest {
  id: string;
  updateTaskListDto: UpdateTaskListDto;
}

export interface TaskListsControllerUpdateOrderRequest {
  id: string;
  updateTaskListOrderDto: UpdateTaskListOrderDto;
}

/**
 *
 */
export class TaskListsApi extends runtime.BaseAPI {
  /**
   * Creates request options for taskListsControllerCreate without sending the request
   */
  async taskListsControllerCreateRequestOpts(
    requestParameters: TaskListsControllerCreateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['createTaskListDto'] == null) {
      throw new runtime.RequiredError(
        'createTaskListDto',
        'Required parameter "createTaskListDto" was null or undefined when calling taskListsControllerCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/task-lists`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateTaskListDtoToJSON(requestParameters['createTaskListDto']),
    };
  }

  /**
   * Create a new task list
   */
  async taskListsControllerCreateRaw(
    requestParameters: TaskListsControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskListsControllerCreate201Response>> {
    const requestOptions = await this.taskListsControllerCreateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskListsControllerCreate201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Create a new task list
   */
  async taskListsControllerCreate(
    requestParameters: TaskListsControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskListsControllerCreate201Response> {
    const response = await this.taskListsControllerCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for taskListsControllerDelete without sending the request
   */
  async taskListsControllerDeleteRequestOpts(
    requestParameters: TaskListsControllerDeleteRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling taskListsControllerDelete().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/task-lists/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete a task list
   */
  async taskListsControllerDeleteRaw(
    requestParameters: TaskListsControllerDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.taskListsControllerDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a task list
   */
  async taskListsControllerDelete(
    requestParameters: TaskListsControllerDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.taskListsControllerDeleteRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for taskListsControllerFindAll without sending the request
   */
  async taskListsControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/task-lists`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get all task lists for the authenticated user
   */
  async taskListsControllerFindAllRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskListsControllerFindAll200Response>> {
    const requestOptions = await this.taskListsControllerFindAllRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskListsControllerFindAll200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get all task lists for the authenticated user
   */
  async taskListsControllerFindAll(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskListsControllerFindAll200Response> {
    const response = await this.taskListsControllerFindAllRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for taskListsControllerUpdate without sending the request
   */
  async taskListsControllerUpdateRequestOpts(
    requestParameters: TaskListsControllerUpdateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling taskListsControllerUpdate().',
      );
    }

    if (requestParameters['updateTaskListDto'] == null) {
      throw new runtime.RequiredError(
        'updateTaskListDto',
        'Required parameter "updateTaskListDto" was null or undefined when calling taskListsControllerUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/task-lists/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateTaskListDtoToJSON(requestParameters['updateTaskListDto']),
    };
  }

  /**
   * Update task list name
   */
  async taskListsControllerUpdateRaw(
    requestParameters: TaskListsControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskListsControllerCreate201Response>> {
    const requestOptions = await this.taskListsControllerUpdateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskListsControllerCreate201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Update task list name
   */
  async taskListsControllerUpdate(
    requestParameters: TaskListsControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskListsControllerCreate201Response> {
    const response = await this.taskListsControllerUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for taskListsControllerUpdateOrder without sending the request
   */
  async taskListsControllerUpdateOrderRequestOpts(
    requestParameters: TaskListsControllerUpdateOrderRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling taskListsControllerUpdateOrder().',
      );
    }

    if (requestParameters['updateTaskListOrderDto'] == null) {
      throw new runtime.RequiredError(
        'updateTaskListOrderDto',
        'Required parameter "updateTaskListOrderDto" was null or undefined when calling taskListsControllerUpdateOrder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/task-lists/{id}/order`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateTaskListOrderDtoToJSON(requestParameters['updateTaskListOrderDto']),
    };
  }

  /**
   * Update task list order
   */
  async taskListsControllerUpdateOrderRaw(
    requestParameters: TaskListsControllerUpdateOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskListsControllerCreate201Response>> {
    const requestOptions = await this.taskListsControllerUpdateOrderRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskListsControllerCreate201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Update task list order
   */
  async taskListsControllerUpdateOrder(
    requestParameters: TaskListsControllerUpdateOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskListsControllerCreate201Response> {
    const response = await this.taskListsControllerUpdateOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
