/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.ts';
import type {
  CreateTaskDto,
  MoveTaskDto,
  TasksControllerCreate201Response,
  TasksControllerFindAll200Response,
  UpdateTaskDto,
  UpdateTaskOrderDto,
} from '../models/index.ts';
import {
  CreateTaskDtoFromJSON,
  CreateTaskDtoToJSON,
  MoveTaskDtoFromJSON,
  MoveTaskDtoToJSON,
  TasksControllerCreate201ResponseFromJSON,
  TasksControllerCreate201ResponseToJSON,
  TasksControllerFindAll200ResponseFromJSON,
  TasksControllerFindAll200ResponseToJSON,
  UpdateTaskDtoFromJSON,
  UpdateTaskDtoToJSON,
  UpdateTaskOrderDtoFromJSON,
  UpdateTaskOrderDtoToJSON,
} from '../models/index.ts';

export interface TasksControllerCreateRequest {
  listId: string;
  createTaskDto: CreateTaskDto;
}

export interface TasksControllerDeleteRequest {
  id: string;
}

export interface TasksControllerFindAllRequest {
  listId: string;
}

export interface TasksControllerMoveRequest {
  id: string;
  moveTaskDto: MoveTaskDto;
}

export interface TasksControllerUpdateRequest {
  id: string;
  updateTaskDto: UpdateTaskDto;
}

export interface TasksControllerUpdateOrderRequest {
  id: string;
  updateTaskOrderDto: UpdateTaskOrderDto;
}

/**
 *
 */
export class TasksApi extends runtime.BaseAPI {
  /**
   * Creates request options for tasksControllerCreate without sending the request
   */
  async tasksControllerCreateRequestOpts(
    requestParameters: TasksControllerCreateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['listId'] == null) {
      throw new runtime.RequiredError(
        'listId',
        'Required parameter "listId" was null or undefined when calling tasksControllerCreate().',
      );
    }

    if (requestParameters['createTaskDto'] == null) {
      throw new runtime.RequiredError(
        'createTaskDto',
        'Required parameter "createTaskDto" was null or undefined when calling tasksControllerCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/task-lists/{listId}/tasks`;
    urlPath = urlPath.replace(
      `{${'listId'}}`,
      encodeURIComponent(String(requestParameters['listId'])),
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateTaskDtoToJSON(requestParameters['createTaskDto']),
    };
  }

  /**
   * Create a new task in a list
   */
  async tasksControllerCreateRaw(
    requestParameters: TasksControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TasksControllerCreate201Response>> {
    const requestOptions = await this.tasksControllerCreateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TasksControllerCreate201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Create a new task in a list
   */
  async tasksControllerCreate(
    requestParameters: TasksControllerCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TasksControllerCreate201Response> {
    const response = await this.tasksControllerCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for tasksControllerDelete without sending the request
   */
  async tasksControllerDeleteRequestOpts(
    requestParameters: TasksControllerDeleteRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling tasksControllerDelete().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/tasks/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete a task
   */
  async tasksControllerDeleteRaw(
    requestParameters: TasksControllerDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.tasksControllerDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a task
   */
  async tasksControllerDelete(
    requestParameters: TasksControllerDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.tasksControllerDeleteRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for tasksControllerFindAll without sending the request
   */
  async tasksControllerFindAllRequestOpts(
    requestParameters: TasksControllerFindAllRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['listId'] == null) {
      throw new runtime.RequiredError(
        'listId',
        'Required parameter "listId" was null or undefined when calling tasksControllerFindAll().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/task-lists/{listId}/tasks`;
    urlPath = urlPath.replace(
      `{${'listId'}}`,
      encodeURIComponent(String(requestParameters['listId'])),
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get all tasks for a task list
   */
  async tasksControllerFindAllRaw(
    requestParameters: TasksControllerFindAllRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TasksControllerFindAll200Response>> {
    const requestOptions = await this.tasksControllerFindAllRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TasksControllerFindAll200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get all tasks for a task list
   */
  async tasksControllerFindAll(
    requestParameters: TasksControllerFindAllRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TasksControllerFindAll200Response> {
    const response = await this.tasksControllerFindAllRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for tasksControllerMove without sending the request
   */
  async tasksControllerMoveRequestOpts(
    requestParameters: TasksControllerMoveRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling tasksControllerMove().',
      );
    }

    if (requestParameters['moveTaskDto'] == null) {
      throw new runtime.RequiredError(
        'moveTaskDto',
        'Required parameter "moveTaskDto" was null or undefined when calling tasksControllerMove().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/tasks/{id}/move`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: MoveTaskDtoToJSON(requestParameters['moveTaskDto']),
    };
  }

  /**
   * Move a task to a different list
   */
  async tasksControllerMoveRaw(
    requestParameters: TasksControllerMoveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TasksControllerCreate201Response>> {
    const requestOptions = await this.tasksControllerMoveRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TasksControllerCreate201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Move a task to a different list
   */
  async tasksControllerMove(
    requestParameters: TasksControllerMoveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TasksControllerCreate201Response> {
    const response = await this.tasksControllerMoveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for tasksControllerUpdate without sending the request
   */
  async tasksControllerUpdateRequestOpts(
    requestParameters: TasksControllerUpdateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling tasksControllerUpdate().',
      );
    }

    if (requestParameters['updateTaskDto'] == null) {
      throw new runtime.RequiredError(
        'updateTaskDto',
        'Required parameter "updateTaskDto" was null or undefined when calling tasksControllerUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/tasks/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateTaskDtoToJSON(requestParameters['updateTaskDto']),
    };
  }

  /**
   * Update a task
   */
  async tasksControllerUpdateRaw(
    requestParameters: TasksControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TasksControllerCreate201Response>> {
    const requestOptions = await this.tasksControllerUpdateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TasksControllerCreate201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Update a task
   */
  async tasksControllerUpdate(
    requestParameters: TasksControllerUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TasksControllerCreate201Response> {
    const response = await this.tasksControllerUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for tasksControllerUpdateOrder without sending the request
   */
  async tasksControllerUpdateOrderRequestOpts(
    requestParameters: TasksControllerUpdateOrderRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling tasksControllerUpdateOrder().',
      );
    }

    if (requestParameters['updateTaskOrderDto'] == null) {
      throw new runtime.RequiredError(
        'updateTaskOrderDto',
        'Required parameter "updateTaskOrderDto" was null or undefined when calling tasksControllerUpdateOrder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/tasks/{id}/order`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateTaskOrderDtoToJSON(requestParameters['updateTaskOrderDto']),
    };
  }

  /**
   * Update task order within its list
   */
  async tasksControllerUpdateOrderRaw(
    requestParameters: TasksControllerUpdateOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TasksControllerCreate201Response>> {
    const requestOptions = await this.tasksControllerUpdateOrderRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TasksControllerCreate201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Update task order within its list
   */
  async tasksControllerUpdateOrder(
    requestParameters: TasksControllerUpdateOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TasksControllerCreate201Response> {
    const response = await this.tasksControllerUpdateOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
