/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { User } from './User.ts';
import { UserFromJSON, UserFromJSONTyped, UserToJSON, UserToJSONTyped } from './User.ts';

/**
 *
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
  /**
   *
   * @type {string}
   * @memberof AuthResponse
   */
  accessToken: string;
  /**
   *
   * @type {User}
   * @memberof AuthResponse
   */
  user: User;
}

/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
  if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
  if (!('user' in value) || value['user'] === undefined) return false;
  return true;
}

export function AuthResponseFromJSON(json: any): AuthResponse {
  return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponse {
  if (json == null) {
    return json;
  }
  return {
    accessToken: json['accessToken'],
    user: UserFromJSON(json['user']),
  };
}

export function AuthResponseToJSON(json: any): AuthResponse {
  return AuthResponseToJSONTyped(json, false);
}

export function AuthResponseToJSONTyped(
  value?: AuthResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    accessToken: value['accessToken'],
    user: UserToJSON(value['user']),
  };
}
