/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { AuthResponse } from './AuthResponse.ts';
import {
  AuthResponseFromJSON,
  AuthResponseFromJSONTyped,
  AuthResponseToJSON,
  AuthResponseToJSONTyped,
} from './AuthResponse.ts';

/**
 *
 * @export
 * @interface AuthControllerRegister201Response
 */
export interface AuthControllerRegister201Response {
  /**
   *
   * @type {AuthResponse}
   * @memberof AuthControllerRegister201Response
   */
  data?: AuthResponse;
  /**
   *
   * @type {string}
   * @memberof AuthControllerRegister201Response
   */
  timestamp?: string;
}

/**
 * Check if a given object implements the AuthControllerRegister201Response interface.
 */
export function instanceOfAuthControllerRegister201Response(
  value: object,
): value is AuthControllerRegister201Response {
  return true;
}

export function AuthControllerRegister201ResponseFromJSON(
  json: any,
): AuthControllerRegister201Response {
  return AuthControllerRegister201ResponseFromJSONTyped(json, false);
}

export function AuthControllerRegister201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthControllerRegister201Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : AuthResponseFromJSON(json['data']),
    timestamp: json['timestamp'] == null ? undefined : json['timestamp'],
  };
}

export function AuthControllerRegister201ResponseToJSON(
  json: any,
): AuthControllerRegister201Response {
  return AuthControllerRegister201ResponseToJSONTyped(json, false);
}

export function AuthControllerRegister201ResponseToJSONTyped(
  value?: AuthControllerRegister201Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: AuthResponseToJSON(value['data']),
    timestamp: value['timestamp'],
  };
}
