/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface CreateTaskListDto
 */
export interface CreateTaskListDto {
  /**
   *
   * @type {string}
   * @memberof CreateTaskListDto
   */
  name: string;
}

/**
 * Check if a given object implements the CreateTaskListDto interface.
 */
export function instanceOfCreateTaskListDto(value: object): value is CreateTaskListDto {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreateTaskListDtoFromJSON(json: any): CreateTaskListDto {
  return CreateTaskListDtoFromJSONTyped(json, false);
}

export function CreateTaskListDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTaskListDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function CreateTaskListDtoToJSON(json: any): CreateTaskListDto {
  return CreateTaskListDtoToJSONTyped(json, false);
}

export function CreateTaskListDtoToJSONTyped(
  value?: CreateTaskListDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
