/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface CreateTaskDto
 */
export interface CreateTaskDto {
  /**
   *
   * @type {string}
   * @memberof CreateTaskDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateTaskDto
   */
  notes?: string;
}

/**
 * Check if a given object implements the CreateTaskDto interface.
 */
export function instanceOfCreateTaskDto(value: object): value is CreateTaskDto {
  if (!('title' in value) || value['title'] === undefined) return false;
  return true;
}

export function CreateTaskDtoFromJSON(json: any): CreateTaskDto {
  return CreateTaskDtoFromJSONTyped(json, false);
}

export function CreateTaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskDto {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    notes: json['notes'] == null ? undefined : json['notes'],
  };
}

export function CreateTaskDtoToJSON(json: any): CreateTaskDto {
  return CreateTaskDtoToJSONTyped(json, false);
}

export function CreateTaskDtoToJSONTyped(
  value?: CreateTaskDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    notes: value['notes'],
  };
}
