/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface HealthControllerCheck200Response
 */
export interface HealthControllerCheck200Response {
  /**
   *
   * @type {string}
   * @memberof HealthControllerCheck200Response
   */
  status?: string;
}

/**
 * Check if a given object implements the HealthControllerCheck200Response interface.
 */
export function instanceOfHealthControllerCheck200Response(
  value: object,
): value is HealthControllerCheck200Response {
  return true;
}

export function HealthControllerCheck200ResponseFromJSON(
  json: any,
): HealthControllerCheck200Response {
  return HealthControllerCheck200ResponseFromJSONTyped(json, false);
}

export function HealthControllerCheck200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HealthControllerCheck200Response {
  if (json == null) {
    return json;
  }
  return {
    status: json['status'] == null ? undefined : json['status'],
  };
}

export function HealthControllerCheck200ResponseToJSON(
  json: any,
): HealthControllerCheck200Response {
  return HealthControllerCheck200ResponseToJSONTyped(json, false);
}

export function HealthControllerCheck200ResponseToJSONTyped(
  value?: HealthControllerCheck200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value['status'],
  };
}
