/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface MoveTaskDto
 */
export interface MoveTaskDto {
  /**
   *
   * @type {string}
   * @memberof MoveTaskDto
   */
  targetListId: string;
  /**
   *
   * @type {number}
   * @memberof MoveTaskDto
   */
  order?: number;
}

/**
 * Check if a given object implements the MoveTaskDto interface.
 */
export function instanceOfMoveTaskDto(value: object): value is MoveTaskDto {
  if (!('targetListId' in value) || value['targetListId'] === undefined) return false;
  return true;
}

export function MoveTaskDtoFromJSON(json: any): MoveTaskDto {
  return MoveTaskDtoFromJSONTyped(json, false);
}

export function MoveTaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveTaskDto {
  if (json == null) {
    return json;
  }
  return {
    targetListId: json['targetListId'],
    order: json['order'] == null ? undefined : json['order'],
  };
}

export function MoveTaskDtoToJSON(json: any): MoveTaskDto {
  return MoveTaskDtoToJSONTyped(json, false);
}

export function MoveTaskDtoToJSONTyped(
  value?: MoveTaskDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    targetListId: value['targetListId'],
    order: value['order'],
  };
}
