/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TaskList } from './TaskList.ts';
import {
  TaskListFromJSON,
  TaskListFromJSONTyped,
  TaskListToJSON,
  TaskListToJSONTyped,
} from './TaskList.ts';

/**
 *
 * @export
 * @interface TaskListsControllerFindAll200Response
 */
export interface TaskListsControllerFindAll200Response {
  /**
   *
   * @type {Array<TaskList>}
   * @memberof TaskListsControllerFindAll200Response
   */
  data?: Array<TaskList>;
  /**
   *
   * @type {string}
   * @memberof TaskListsControllerFindAll200Response
   */
  timestamp?: string;
}

/**
 * Check if a given object implements the TaskListsControllerFindAll200Response interface.
 */
export function instanceOfTaskListsControllerFindAll200Response(
  value: object,
): value is TaskListsControllerFindAll200Response {
  return true;
}

export function TaskListsControllerFindAll200ResponseFromJSON(
  json: any,
): TaskListsControllerFindAll200Response {
  return TaskListsControllerFindAll200ResponseFromJSONTyped(json, false);
}

export function TaskListsControllerFindAll200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TaskListsControllerFindAll200Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : (json['data'] as Array<any>).map(TaskListFromJSON),
    timestamp: json['timestamp'] == null ? undefined : json['timestamp'],
  };
}

export function TaskListsControllerFindAll200ResponseToJSON(
  json: any,
): TaskListsControllerFindAll200Response {
  return TaskListsControllerFindAll200ResponseToJSONTyped(json, false);
}

export function TaskListsControllerFindAll200ResponseToJSONTyped(
  value?: TaskListsControllerFindAll200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: value['data'] == null ? undefined : (value['data'] as Array<any>).map(TaskListToJSON),
    timestamp: value['timestamp'],
  };
}
