/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { TaskList } from './TaskList.ts';
import {
  TaskListFromJSON,
  TaskListFromJSONTyped,
  TaskListToJSON,
  TaskListToJSONTyped,
} from './TaskList.ts';

/**
 *
 * @export
 * @interface TaskListsControllerCreate201Response
 */
export interface TaskListsControllerCreate201Response {
  /**
   *
   * @type {TaskList}
   * @memberof TaskListsControllerCreate201Response
   */
  data?: TaskList;
  /**
   *
   * @type {string}
   * @memberof TaskListsControllerCreate201Response
   */
  timestamp?: string;
}

/**
 * Check if a given object implements the TaskListsControllerCreate201Response interface.
 */
export function instanceOfTaskListsControllerCreate201Response(
  value: object,
): value is TaskListsControllerCreate201Response {
  return true;
}

export function TaskListsControllerCreate201ResponseFromJSON(
  json: any,
): TaskListsControllerCreate201Response {
  return TaskListsControllerCreate201ResponseFromJSONTyped(json, false);
}

export function TaskListsControllerCreate201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TaskListsControllerCreate201Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : TaskListFromJSON(json['data']),
    timestamp: json['timestamp'] == null ? undefined : json['timestamp'],
  };
}

export function TaskListsControllerCreate201ResponseToJSON(
  json: any,
): TaskListsControllerCreate201Response {
  return TaskListsControllerCreate201ResponseToJSONTyped(json, false);
}

export function TaskListsControllerCreate201ResponseToJSONTyped(
  value?: TaskListsControllerCreate201Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: TaskListToJSON(value['data']),
    timestamp: value['timestamp'],
  };
}
