/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface TaskList
 */
export interface TaskList {
  /**
   *
   * @type {string}
   * @memberof TaskList
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TaskList
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof TaskList
   */
  order: number;
  /**
   *
   * @type {string}
   * @memberof TaskList
   */
  userId: string;
  /**
   *
   * @type {Date}
   * @memberof TaskList
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof TaskList
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the TaskList interface.
 */
export function instanceOfTaskList(value: object): value is TaskList {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('order' in value) || value['order'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function TaskListFromJSON(json: any): TaskList {
  return TaskListFromJSONTyped(json, false);
}

export function TaskListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskList {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    order: json['order'],
    userId: json['userId'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  };
}

export function TaskListToJSON(json: any): TaskList {
  return TaskListToJSONTyped(json, false);
}

export function TaskListToJSONTyped(
  value?: TaskList | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    order: value['order'],
    userId: value['userId'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  };
}
