/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { Task } from './Task.ts';
import { TaskFromJSON, TaskFromJSONTyped, TaskToJSON, TaskToJSONTyped } from './Task.ts';

/**
 *
 * @export
 * @interface TasksControllerFindAll200Response
 */
export interface TasksControllerFindAll200Response {
  /**
   *
   * @type {Array<Task>}
   * @memberof TasksControllerFindAll200Response
   */
  data?: Array<Task>;
  /**
   *
   * @type {string}
   * @memberof TasksControllerFindAll200Response
   */
  timestamp?: string;
}

/**
 * Check if a given object implements the TasksControllerFindAll200Response interface.
 */
export function instanceOfTasksControllerFindAll200Response(
  value: object,
): value is TasksControllerFindAll200Response {
  return true;
}

export function TasksControllerFindAll200ResponseFromJSON(
  json: any,
): TasksControllerFindAll200Response {
  return TasksControllerFindAll200ResponseFromJSONTyped(json, false);
}

export function TasksControllerFindAll200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TasksControllerFindAll200Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : (json['data'] as Array<any>).map(TaskFromJSON),
    timestamp: json['timestamp'] == null ? undefined : json['timestamp'],
  };
}

export function TasksControllerFindAll200ResponseToJSON(
  json: any,
): TasksControllerFindAll200Response {
  return TasksControllerFindAll200ResponseToJSONTyped(json, false);
}

export function TasksControllerFindAll200ResponseToJSONTyped(
  value?: TasksControllerFindAll200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: value['data'] == null ? undefined : (value['data'] as Array<any>).map(TaskToJSON),
    timestamp: value['timestamp'],
  };
}
