/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface Task
 */
export interface Task {
  /**
   *
   * @type {string}
   * @memberof Task
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  notes?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof Task
   */
  completed: boolean;
  /**
   *
   * @type {number}
   * @memberof Task
   */
  order: number;
  /**
   *
   * @type {string}
   * @memberof Task
   */
  taskListId: string;
  /**
   *
   * @type {Date}
   * @memberof Task
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Task
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('completed' in value) || value['completed'] === undefined) return false;
  if (!('order' in value) || value['order'] === undefined) return false;
  if (!('taskListId' in value) || value['taskListId'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function TaskFromJSON(json: any): Task {
  return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    notes: json['notes'] == null ? undefined : json['notes'],
    completed: json['completed'],
    order: json['order'],
    taskListId: json['taskListId'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  };
}

export function TaskToJSON(json: any): Task {
  return TaskToJSONTyped(json, false);
}

export function TaskToJSONTyped(value?: Task | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    title: value['title'],
    notes: value['notes'],
    completed: value['completed'],
    order: value['order'],
    taskListId: value['taskListId'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  };
}
