/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
import type { Task } from './Task.ts';
import { TaskFromJSON, TaskFromJSONTyped, TaskToJSON, TaskToJSONTyped } from './Task.ts';

/**
 *
 * @export
 * @interface TasksControllerCreate201Response
 */
export interface TasksControllerCreate201Response {
  /**
   *
   * @type {Task}
   * @memberof TasksControllerCreate201Response
   */
  data?: Task;
  /**
   *
   * @type {string}
   * @memberof TasksControllerCreate201Response
   */
  timestamp?: string;
}

/**
 * Check if a given object implements the TasksControllerCreate201Response interface.
 */
export function instanceOfTasksControllerCreate201Response(
  value: object,
): value is TasksControllerCreate201Response {
  return true;
}

export function TasksControllerCreate201ResponseFromJSON(
  json: any,
): TasksControllerCreate201Response {
  return TasksControllerCreate201ResponseFromJSONTyped(json, false);
}

export function TasksControllerCreate201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TasksControllerCreate201Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : TaskFromJSON(json['data']),
    timestamp: json['timestamp'] == null ? undefined : json['timestamp'],
  };
}

export function TasksControllerCreate201ResponseToJSON(
  json: any,
): TasksControllerCreate201Response {
  return TasksControllerCreate201ResponseToJSONTyped(json, false);
}

export function TasksControllerCreate201ResponseToJSONTyped(
  value?: TasksControllerCreate201Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: TaskToJSON(value['data']),
    timestamp: value['timestamp'],
  };
}
