/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface UpdateTaskOrderDto
 */
export interface UpdateTaskOrderDto {
  /**
   *
   * @type {number}
   * @memberof UpdateTaskOrderDto
   */
  order: number;
}

/**
 * Check if a given object implements the UpdateTaskOrderDto interface.
 */
export function instanceOfUpdateTaskOrderDto(value: object): value is UpdateTaskOrderDto {
  if (!('order' in value) || value['order'] === undefined) return false;
  return true;
}

export function UpdateTaskOrderDtoFromJSON(json: any): UpdateTaskOrderDto {
  return UpdateTaskOrderDtoFromJSONTyped(json, false);
}

export function UpdateTaskOrderDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTaskOrderDto {
  if (json == null) {
    return json;
  }
  return {
    order: json['order'],
  };
}

export function UpdateTaskOrderDtoToJSON(json: any): UpdateTaskOrderDto {
  return UpdateTaskOrderDtoToJSONTyped(json, false);
}

export function UpdateTaskOrderDtoToJSONTyped(
  value?: UpdateTaskOrderDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    order: value['order'],
  };
}
