/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface UpdateTaskDto
 */
export interface UpdateTaskDto {
  /**
   *
   * @type {string}
   * @memberof UpdateTaskDto
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateTaskDto
   */
  notes?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof UpdateTaskDto
   */
  completed?: boolean;
}

/**
 * Check if a given object implements the UpdateTaskDto interface.
 */
export function instanceOfUpdateTaskDto(value: object): value is UpdateTaskDto {
  return true;
}

export function UpdateTaskDtoFromJSON(json: any): UpdateTaskDto {
  return UpdateTaskDtoFromJSONTyped(json, false);
}

export function UpdateTaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskDto {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'] == null ? undefined : json['title'],
    notes: json['notes'] == null ? undefined : json['notes'],
    completed: json['completed'] == null ? undefined : json['completed'],
  };
}

export function UpdateTaskDtoToJSON(json: any): UpdateTaskDto {
  return UpdateTaskDtoToJSONTyped(json, false);
}

export function UpdateTaskDtoToJSONTyped(
  value?: UpdateTaskDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    notes: value['notes'],
    completed: value['completed'],
  };
}
