/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface UpdateTaskListOrderDto
 */
export interface UpdateTaskListOrderDto {
  /**
   *
   * @type {number}
   * @memberof UpdateTaskListOrderDto
   */
  order: number;
}

/**
 * Check if a given object implements the UpdateTaskListOrderDto interface.
 */
export function instanceOfUpdateTaskListOrderDto(value: object): value is UpdateTaskListOrderDto {
  if (!('order' in value) || value['order'] === undefined) return false;
  return true;
}

export function UpdateTaskListOrderDtoFromJSON(json: any): UpdateTaskListOrderDto {
  return UpdateTaskListOrderDtoFromJSONTyped(json, false);
}

export function UpdateTaskListOrderDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTaskListOrderDto {
  if (json == null) {
    return json;
  }
  return {
    order: json['order'],
  };
}

export function UpdateTaskListOrderDtoToJSON(json: any): UpdateTaskListOrderDto {
  return UpdateTaskListOrderDtoToJSONTyped(json, false);
}

export function UpdateTaskListOrderDtoToJSONTyped(
  value?: UpdateTaskListOrderDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    order: value['order'],
  };
}
