/* tslint:disable */
/* eslint-disable */
/**
 * Todo App API
 * Todo App REST API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface UpdateTaskListDto
 */
export interface UpdateTaskListDto {
  /**
   *
   * @type {string}
   * @memberof UpdateTaskListDto
   */
  name: string;
}

/**
 * Check if a given object implements the UpdateTaskListDto interface.
 */
export function instanceOfUpdateTaskListDto(value: object): value is UpdateTaskListDto {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function UpdateTaskListDtoFromJSON(json: any): UpdateTaskListDto {
  return UpdateTaskListDtoFromJSONTyped(json, false);
}

export function UpdateTaskListDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTaskListDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function UpdateTaskListDtoToJSON(json: any): UpdateTaskListDto {
  return UpdateTaskListDtoToJSONTyped(json, false);
}

export function UpdateTaskListDtoToJSONTyped(
  value?: UpdateTaskListDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
